language: python
os: linux
cache: pip
env:
  global:
    - PGPORT=5433
    - POSTGRES_PORT=5433
jobs:
    include:
        - name: "Python 3.8 on Xenial Linux"
          dist: xenial
          os: linux
          python: 3.8        # this works for Linux but is ignored on macOS or Windows
        - name: "Python 3.8 on Bionic Linux"
          dist: bionic
          os: linux
          python: 3.8        # this works for Linux but is ignored on macOS or Windows
#        - name: "Python 3.8 on Windows"
#          os: windows       # Windows 10.0.17134 N/A Build 17134
#          language: shell   # 'language: python' is an error on Travis CI Windows
#          before_install:
#              - choco install python --version 3.8.0
#              - python -m pip install --upgrade pip
#          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo apt-get install -y binutils libproj-dev gdal-bin postgis postgresql-12-postgis-3
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
before_script:
    - psql -U postgres -f utils/database/dev.sql
    #- psql -U postgres -c 'create database travis_ci_test;'
    #- psql -U postgres -c "create extension postgis"
script:
    - python manage.py makemigrations
    - python manage.py test
    - pytest
services:
    - postgresql
    - redis
addons:
    postgresql: 12.2
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-12-postgis-3
