langauge: python
os: linux
#env:
#  global:
#    - PGPORT=5433
#    - POSTGRES_PORT=5433
jobs:
    include:
        - stage: testing
          name: "Python 3.8 on Xenial Linux"
          cache: pip
          dist: xenial
          os: linux
          python: 3.8
          env:
              - PGPORT=5433
              - POSTGRES_PORT=5433
          before_install:
              - sudo apt-get update
              - sudo apt-get --yes remove postgresql\*
              - sudo apt-get install -y postgresql-12 postgresql-client-12
              - sudo apt-get install -y binutils libproj-dev gdal-bin postgis postgresql-12-postgis-3
              - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
              - sudo service postgresql restart 12
          install:
              - pip install --upgrade pip
              - pip install -r requirements.txt
          before_script:
              - psql -U postgres -f utils/database/dev.sql
          script:
              - python manage.py makemigrations
              - python manage.py migrate
              - python manage.py test
              - pytest
          services:
              - postgresql
              - redis
          addons:
              postgresql: 12.2
              apt:
                  packages:
                      - postgresql-12
                      - postgresql-client-12
                      - postgresql-12-postgis-3

        - name: "Python 3.8 on Bionic Linux"
          cache: pip
          dist: bionic
          os: linux
          python: 3.8
          env:
              - PGPORT=5433
              - POSTGRES_PORT=5433
          before_install:
              - sudo apt-get update
              - sudo apt-get --yes remove postgresql\*
              - sudo apt-get install -y postgresql-12 postgresql-client-12
              - sudo apt-get install -y binutils libproj-dev gdal-bin postgis postgresql-12-postgis-3
              - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
              - sudo service postgresql restart 12
          install:
              - pip install --upgrade pip
              - pip install -r requirements.txt
          before_script:
              - psql -U postgres -f utils/database/dev.sql
          script:
              - python manage.py makemigrations
              - python manage.py migrate
              - python manage.py test
              - pytest
          services:
              - postgresql
              - redis
          addons:
              postgresql: 12.2
              apt:
                  packages:
                      - postgresql-12
                      - postgresql-client-12
                      - postgresql-12-postgis-3

#        - name: "Python 3.8 on Windows"
#          os: windows       # Windows 10.0.17134 N/A Build 17134
#          language: shell   # 'language: python' is an error on Travis CI Windows
#          before_install:
#              - choco install python --version 3.8.0
#              - python -m pip install --upgrade pip
#          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

        #- stage: integrating
        - name: "Docker Integration Testing"
          dist: bionic
          os: linux
          install:
              - docker-compose up -d
          before_script:
              - mkdir -p ./volumes/db/var/lib/postgres_data
          script:
              - docker ps | grep -q iotsite_iotsite
              - docker ps | grep -q postgis
              - docker container ls
              - docker logs --tail --follow --timestamps `docker container ls | grep postgis | cut -f 1 -d ' '`
              - docker exec -it `docker container ls | grep iotsite_iotsite | cut -f 1 -d ' '` ./manage.py test
          services:
              - docker

        - stage: deploying
          name: "Deploy gh-pages Documentation"
          cache: pip
          python: 3.8
          before_script:
            - pip install -r docs/requirements.txt
          script: #./docs/deploy_gh_pages.sh
            - cd docs
            - make html
            - touch build/html/.nojekyll
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: docs/build/html/
              commit_message: "Built Tag ${TRAVIS_TAG} on Build ${TRAVIS_BUILD_NUMBER} for ${TRAVIS_COMMIT}"
              on:
                  branch: master

