version: '3'
services:
    postgis:
        image: kartoza/postgis:latest
        environment:
            - POSTGRES_DBNAME=geodjango
            - POSTGRES_USER=geo
            - POSTGRES_PASS=geo
            - ALLOW_IP_RANGE=0.0.0.0/0
        restart: unless-stopped
#        networks:
#            - backend
#        ports:
#            - 5432:5432
#            - 1234:1234
    iotsite:
        build: .
        depends_on:
            - postgis
        command: bash -c "./manage.py wait_for_db &&
                          ./manage.py makemigrations &&
                          ./manage.py migrate &&
                          ./manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 81:8000
        restart: unless-stopped

#        networks:
#            - backend
#networks:
#    backend:
