# Generated by Django 2.2.4 on 2019-09-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('package_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('relay_id', models.CharField(blank=True, default='', max_length=100)),
                ('sensor_id', models.CharField(blank=True, default='', max_length=100)),
                ('sensor_type', models.CharField(blank=True, default='', max_length=100)),
                ('units', models.DecimalField(decimal_places=3, max_digits=6)),
                ('data', models.CharField(blank=True, default='', max_length=1)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('altitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('climb', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
